name: Deploy Laravel App

on:
  push:
    branches:
      - main  # trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP (for Laravel)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp.coderpirate.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Path to your project files
        server-dir: /home/username/public_html/yourproject
