name: Publish Website to Web Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy website on every commit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, zip, pdo, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: |
        php artisan key:generate --force
        echo "APP_KEY=$(php artisan key:generate --show)" >> .env

    # - name: Set environment variables
    #   run: |
    #     echo "APP_ENV=production" >> .env
    #     echo "APP_DEBUG=false" >> .env
    #     echo "DB_CONNECTION=mysql" >> .env
    #     echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
    #     echo "DB_PORT=3306" >> .env
    #     echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
    #     echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
    #     echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    # - name: Run migrations
    #   run: php artisan migrate --force

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm install

    # - name: Compile assets
    #   run: npm run production

    - name: Optimize Laravel
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: './'
